name: rating-api-testing
on:
  push:
    branches:
      - testing
jobs:
  rating-api-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@master
      name: Login & checkout
      with:
        ref: testing

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test code
      run: | 
        pip install tox
        tox -e py

    - name: Build & push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: alterwayrnd/rating-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        docker: Dockerfile
        tags: "latest,testing"